package debugdef

const (
	DEBUG_LEVEL_ERROR   = 1
	DEBUG_LEVEL_SECURED = 2
	DEBUG_LEVEL_NORMAL  = 3
	DEBUG_LEVEL_TEST    = 4
)

const (
	DEBUG_LEVEL_ERROR_STR   = "ERROR"
	DEBUG_LEVEL_SECURED_STR = "SECURED"
	DEBUG_LEVEL_NORMAL_STR  = "NORMAL"
	DEBUG_LEVEL_TEST_STR    = "TEST"
)
