package functiondef

const (
	FunctionTypeCallMethod                        = "call_method"
	FunctionTypeValidateField                     = "validate_fld"
	FunctionTypeValidateCondition                 = "validate_condition"
	FunctionTypeDBSingleRead                      = "db_single_read"
	FunctionTypeDBMultiRead                       = "db_multi_read"
	FunctionTypeDBInsert                          = "db_insert"
	FunctionTypeDBUpdate                          = "db_update"
	FunctionTypeDBDelete                          = "db_delete"
	FunctionTypeEntitySeqNum                      = "entity_seq_num"
	FunctionTypeCreateObject                      = "create_object"
	FunctionTypeCopyObject                        = "copy_object"
	FunctionTypeCopyArray                         = "copy_array"
	FunctionTypeComposeResponse                   = "compose_response"
	FunctionTypeCreateDBSequence                  = "create_db_sequence"
	FunctionTypeStartLoop                         = "start_loop"
	FunctionTypeEndLoop                           = "end_loop"
	FunctionTypeTransformObject                   = "transform_object"
	FunctionTypeGenCVV                            = "gen_cvv"
	FunctionTypeGenTrackData                      = "gen_track_data"
	FunctionTypeCreateMapArray                    = "create_map_array"
	FunctionTypeMathFunction                      = "math_function"
	FunctionTypeGenRandomKey                      = "gen_random_key"
	FunctionTypeRawQuery                          = "raw_query"
	FunctionTypeSendEmail                         = "send_email"
	FunctionTypeSendSMS                           = "send_sms"
	FunctionTypeGenPersoFile                      = "gen_perso_file"
	FunctionTypeVerifyToken                       = "verify_token"
	FunctionTypeGenToken                          = "gen_token"
	FunctionTypeSendToService                     = "send_to_service"
	FunctionTypeDecodeToken                       = "decode_token"
	FunctionTypeCreateEmptyList                   = "create_empty_list"
	FunctionTypeSendToBroker                      = "send_to_broker"
	FunctionTypeArithmetic                        = "arith_operation"
	FunctionTypeValidateConditionAndUpdateOnError = "validate_condition_and_update_on_error"
)
